export enum UserRoles {
    ADMIN_DEPARTMENT = 'ADMIN_DEPARTMENT',
    ADMIN_TECHNICIANS = 'ADMIN_TECHNICIANS',
    TECHNICIAN = 'TECHNICIAN',
    ADMIN_LAB = 'ADMIN_LAB',
    ONLY_READ = 'ONLY_READ'
}
